services:
  - type: web
    name: om-paye
    env: docker
    region: oregon
    plan: free
    branch: main
    autoDeploy: true

    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Xmx512m -Xms256m -jar app.jar
    healthCheckPath: /actuator/health

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080

      # --- Database ---
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

      # --- JWT ---
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 86400000

      # --- Brevo ---
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: noreply@ompay.sn
      - key: MAIL_FROM_NAME
        value: OM Pay

      # --- Twilio ---
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false

      # --- Swagger ---
      - key: SWAGGER_ENABLED
        value: true
      - key: SWAGGER_SERVER_PROD_URL
        value: https://om-paye.onrender.com
      - key: SWAGGER_SERVER_LOCAL_URL
        value: http://localhost:5029
