spring:
  application:
    name: om_paye
  profiles:
    active: dev
  messages:
    basename: messages
    encoding: UTF-8
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ERROR
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 5029

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    disable-swagger-default-url: true 
  show-actuator: false


logging:
  level:
    org.springframework.security: DEBUG  
    org.springdoc: DEBUG